### ISSUE TITLE
Symbol not found in flat namespace

### ISSUE THREAD

**Issue by caseydm** [jalan/pdftotext#100]
Hi all. I'm getting this error when trying to import pdftotext in a flask project and cannot figure out how to resolve it.

`ImportError: dlopen(/Users/casey/PycharmProjects/virtual environments/oadoi/lib/python3.9/site-packages/pdftotext.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '__ZN7poppler24set_debug_error_functionEPFvRKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEPvES9_'`

My installation details are:

- Mac M1
- pdftotext version 2.1.5
- Installed poppler with homebrew, set to version 22.04.0
- Ensured poppler visible to pdftotext by setting these environment variables in my shell:
```
export LDFLAGS="-L/opt/homebrew/opt/openssl/lib -L/opt/homebrew/lib $LDFLAGS"
export CPPFLAGS="-I/opt/homebrew/opt/openssl/include -I/opt/homebrew/include $CPPFLAGS"
```

**Comment by jalan** [comment]
Newer versions are more likely to work in your environment. Try again with the latest version.

https://github.com/jalan/pdftotext/blob/master/CHANGES.md

**Comment by caseydm** [comment]
Ok thank you!

**Comment by caseydm** [comment]
Sure! Here are the details:

- MacOS 12.3.1 (iMac with M1 chip)
- Installed python by going to https://www.python.org/downloads/macos/ and downloaded and installed python 3.9.12
- Installed poppler by going into a terminal window and running `brew install poppler`
- I used PyCharm to create a virtual environment for my project, selecting python 3.9
<img width="973" alt="Screen Shot 2022-05-11 at 11 03 05 AM" src="https://user-images.githubusercontent.com/3642984/167895577-35dd90e0-48cc-43e9-b88d-c31dfff89b2a.png">
- Go into the activated environment and install with `pip install -r requirements.txt`. Within the requirements file there is a line pdftotext==2.2.2

Of note I tried to install on a Macbook Pro with similar config and got the same error message. Thank you for any help!

**Comment by gree2** [comment]
(docs) ai@learn % pip freeze | grep pdftotext                                 ~
pdftotext==2.2.2
(docs) ai@learn % python -c 'import pdftotext'                                ~
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dlopen(/Users/ai/opt/anaconda3/envs/docs/lib/python3.10/site-packages/pdftotext.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '__ZN7poppler24set_debug_error_functionEPFvRKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEPvES9_'
(docs) ai@learn [1] %

M2 macOS

**Comment by dmitry-viskov** [comment]
hi there!
Faced with the same issue with M3 MacOS:

```
$ python
Python 3.12.4 (main, Jun 26 2024, 14:44:41) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pdftotext
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/dmitry/.pyenv/versions/ag-venv/lib/python3.12/site-packages/pdftotext.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '__ZN7poppler24set_debug_error_functionEPFvRKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEPvES9_'
```
Tried this using python from `brew` and python from `pyenv`

**Comment by jalan** [comment]
Did you follow the steps in https://github.com/jalan/pdftotext/issues/100#issuecomment-1124001193 ?

Since there's about 9000 ways to install python and set up virtual envs and install libs and install packages, without knowing the details of your particular setup, I can't do much.
