### ISSUE TITLE
Two different text output is returned

### ISSUE THREAD

**Issue by pavankalyan066** [jalan/pdftotext#101]
Myself trying to extract the text using the library, when I try in my local the text is extracted line by line but when I execute it in Docker, the text is not in line by line order.

Could someone please help me to find or fix the issue, I had used version 2.2.0.

**Comment by jalan** [comment]
This is an issue tracker, not a discussion forum. Nobody else knows what software is on your "local" or what you're running in docker. You haven't provided any information to indicate a bug in this package, and you haven't even provided enough information for someone to help you with your own problem. Please don't waste people's time like this.

**Comment by pavankalyan066** [comment]
Sorry, I won't repeat this thing, but one doubt, In local it reads line by line, and docker it is reading in a vertical manner. If you are aware of where is the issue mention it, Thank you.
