### ISSUE TITLE
AttributeError: module 'pdftotext' has no attribute 'PDF'

### ISSUE THREAD

**Issue by vignesh-bosch** [jalan/pdftotext#105]
import pdftotext

# Load your PDF
with open(r"test_batch\test1.pdf", "rb") as f:
    pdf = pdftotext.PDF(f)

# How many pages?
print(len(pdf))

# It returns:

**AttributeError: module 'pdftotext' has no attribute 'PDF'**

**Comment by jalan** [comment]
How did you install the module? Please be thorough.

**Comment by vignesh-bosch** [comment]
#command used to install package.

pip install pdftotext

**Comment by jalan** [comment]
Okay, on what OS? If you actually want help, you need to put in a little more effort, give some kind of information.

**Comment by jalan** [comment]
Nothing useful here so far
