### ISSUE TITLE
Import error when running on MacOs (M1) 

### ISSUE THREAD

**Issue by Ethansev** [jalan/pdftotext#107]
Hi All,
I'm running into this error when importing pdftotext. I've followed the instructions correctly and have tried to reinstall all dependencies including all the brew packages.

`ImportError: dlopen(/Users/ethannguyen/Documents/GitHub/livebuildings/env/lib/python2.7/site-packages/pdftotext.so, 0x0002): symbol not found in flat namespace '__ZN7poppler24set_debug_error_functionEPFvRKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEPvES9_'`

**Comment by jalan** [comment]
Something is wacky with your python environment. Take a look at #100
