### ISSUE TITLE
Can't import on MacOs

### ISSUE THREAD

**Issue by GregDerderian** [jalan/pdftotext#11]
pkg-config and poppler are installed via brew. Then pdftotext is installed via pip. 
When I tried to import it in a Jupyter Notebook (conda env, python3) :

```
ImportError                               Traceback (most recent call last)
<ipython-input-104-46fa7238b159> in <module>()
----> 1 import pdftotext

ImportError: dlopen(/Users/[username]/miniconda3/envs/[env-name]/lib/python3.6/site-packages/pdftotext.cpython-36m-darwin.so, 2): Symbol not found: __ZN7poppler24set_debug_error_functionEPFvRKSsPvES2_
  Referenced from: /Users/[username]/miniconda3/envs/[env-name]/lib/python3.6/site-packages/pdftotext.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/[username]/miniconda3/envs/[env-name]/lib/python3.6/site-packages/pdftotext.cpython-36m-darwin.so
```

**Comment by jalan** [comment]
It looks like there is a conflict between the poppler you installed via brew and another poppler, perhaps installed via conda? I'm not too familiar with conda, but it seems best not to mix conda and brew.

Could you try:
 - uninstall the brew packages
 - make a new conda env
 - in that conda env, conda install pkg-config and poppler
 - in that conda env, pip install pdftotext

**Comment by GregDerderian** [comment]
Thanks Jalan for your reply!
I tried and it didn't work, but the error is different : 
I did : 
```
$ brew uninstall pkg-config poppler
$ conda create envname
$ source activate envname
(envname) $ conda install pip pkg-config poppler
(envname) $ pip install pdftotext
(envname) $ python
(envname) >>> import pdftotext
```

and I get this error : 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/[username]/miniconda3/envs/[envname]/lib/python3.6/site-packages/pdftotext.cpython-36m-darwin.so, 2): Library not loaded: /usr/local/opt/poppler/lib/libpoppler-cpp.0.dylib
  Referenced from: /Users/[username]/miniconda3/envs/[envname]/lib/python3.6/site-packages/pdftotext.cpython-36m-darwin.so
  Reason: image not found
```

any idea ? 
thanks!

**Comment by jalan** [comment]
Hmm, it still looks like there is a conflict between conda libs and some other libs. I wish I had a Mac to try it out. Flying blind here, sorry I can't be more help.

**Comment by Phoehtaung** [comment]
I am using MAC as well and facing this error when I try to import

`In [1]: import pdftotext
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-b47658e7d4bc> in <module>()
----> 1 import pdftotext

ImportError: dlopen(/Users/okar/.virtualenvs/keyboardPDF/lib/python3.6/site-packages/pdftotext.cpython-36m-darwin.so, 2): Symbol not found: __ZN7poppler24set_debug_error_functionEPFvRKSsPvES2_
  Referenced from: /Users/okar/.virtualenvs/keyboardPDF/lib/python3.6/site-packages/pdftotext.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/okar/.virtualenvs/keyboardPDF/lib/python3.6/site-packages/pdftotext.cpython-36m-darwin.so

`

I've tried reinstalling pkg-config and poppler through homebrew still no avail

**Comment by Phoehtaung** [comment]
I am using MAC as well and facing this

'''
import pdftotext
ImportError: dlopen(/Users/username/.virtualenvs/projectname/lib/python3.6/site-packages/pdftotext.cpython-36m-darwin.so, 2): Symbol not found: __ZN7poppler24set_debug_error_functionEPFvRKSsPvES2_
  Referenced from: /Users/username/.virtualenvs/projectname/lib/python3.6/site-packages/pdftotext.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/username/.virtualenvs/projectname/lib/python3.6/site-packages/pdftotext.cpython-36m-darwin.so
'''

**Comment by jalan** [comment]
Works fine on macOS in a virtualenv for me, using python 3.6, poppler, and pkg-config all installed via brew. [This stackoverflow question](https://stackoverflow.com/questions/35006614/what-does-symbol-not-found-expected-in-flat-namespace-actually-mean) might be of some help.

**Comment by TraverseTowner** [comment]
I get the exact same error as Phiehtaung, and I am using MAX as well.

**Comment by jalan** [comment]
Nothing for me to fix here,

**Comment by nsangwan** [comment]
@GregDerderian @TraverseTowner @Phoehtaung - were you able to find a solution? I am facing the same issue.

**Comment by vinaytummarakota** [comment]
@GregDerderian @TraverseTowner I am running into the same issue. I've installed pkg-config and poppler via brew and used pip to install pdftotext. Any way to resolve the issue?
