### ISSUE TITLE
Formatting changed after new install

### ISSUE THREAD

**Issue by tbrownhe** [jalan/pdftotext#110]
I'm running macOS 13.1 with Python 3.10 in a miniconda environment.

I use pdftotext in a project I made a few years ago that parses all my various bank statements so I can see my finances all in one place. The project went stale over the last year. Recently I reinstalled everything from my requirements.txt and it seems that the behavior of pdftotext has changed. Previously, pdftotext output text that had the date and transaction description on the same line. Now, pdftotext completely separates the date and transaction description. They aren't even alternating lines. They are interpreted as being in completely separate text blocks. 

For example, text that used to be read as `10/30 example purchase 1\n10/31 example purchase 2` now reads as `10/30\n10/31\nSome other part of the pdf\nexample purchase 1\nexample purchase 2`. I tried pdftotext on PDFs I had successfully imported over a year ago and the output now is completely garbled.

Any ideas what could have caused this shift in behavior? I tried reverting to older versions of pdftotext, but no luck. Could this be a change in pdftotext's dependencies on mac?

**Comment by jalan** [comment]
Could be due to a change in the underlying poppler library, yeah.

You can try playing with the layout options, `raw` and `physical`, to see if you get better results.

```
$ python
>>> import pdftotext
>>> help(pdftotext.PDF)

Help on class PDF in module pdftotext:

class PDF(builtins.object)
 |  PDF(pdf_file, password="", raw=False, physical=False)
 |  
 |  Args:
 |      pdf_file: A file opened for reading in binary mode.
 |      password: Unlocks the document, if required. Either the owner
 |          password or the user password works.
 |      raw: If True, page text is output in the order it appears in the
 |          content stream.
 |      physical: If True, page text is output in the order it appears on
 |          the page, regardless of columns or other layout features.
 |  
 |      Usually, the most readable output is achieved by using the default
 |      mode, rather than raw or physical.
```

**Comment by jaki** [comment]
Upgraded pdftotext from 2.1.5 to 2.2.2.  Hit this issue with over ten documents.  Inspected one document, and it is just like @tbrownhe describes.

Used `physical=True`, and it's back to what it was before.

**Comment by jalan** [comment]
Physical layout was the default before version 2.2.0, which I considered a bug, because it did not match what the poppler authors recommend. In hindsight, I should have bumped the version to 3.0.0 on that release, since this behavior change is a major change for many users.

In any case, can't change the past, no bug here now.
