### ISSUE TITLE
not able to install in red-hat base image 8 

### ISSUE THREAD

**Issue by tiger-tribe-sunnyraj** [jalan/pdftotext#112]
I am tot able to install pdftotext on to red-hat base image 8 .
Tried steps -- 

- I tried installing with pip -- ``` pip install pdftotext ``` , it gave me error -- poppler not found 
- when i tried installing poppler with command provided ``` sudo yum install gcc-c++ pkgconfig poppler-cpp-devel python3-devel ```
    It showed me error -- unable to find match poppler-cpp-devel  
- I tried installing ``` yum install poppler-qt5 poppler-qt5-devel ``` , same error unable to find match 
- please let me know , if i need to install anything else to work in my os (red-hat base image 8)

**Comment by jalan** [comment]
See https://github.com/jalan/pdftotext/issues/49#issuecomment-548900498
