### ISSUE TITLE
PDF tags after converting tags from PDF

### ISSUE THREAD

**Issue by Wowhere** [jalan/pdftotext#115]
PDF tags after converting tags from PDF

I'am trying to parse one archived Russian newspaper with following code

```
from os import listdir
from os.path import isfile, join
import sys
import pdftotext
from ftfy import fix_text

l = sys.argv[1]
onlyfiles = [f for f in listdir(l) if isfile(join(l, f))]

the_text = ""
for pdf_file in onlyfiles:
    with open(l+pdf_file, "rb") as f:
        pdf = pdftotext.PDF(f)
        the_text += pdf_file+'\n'
        #print(pdf_file)
        for page in pdf:
            the_text += str(page)
            #print(page)
        the_text += str(len(pdf))+'\n'
        #print(len(pdf))

a = open('res.txt', 'w')
ttt = fix_text(the_text)
a.write(ttt)
a.close()
```

and after parsing get following. 
![изображение](https://github.com/jalan/pdftotext/assets/69252550/4807a3c4-501c-4baa-aada-bad28fdd2206)

In PDF relevant text is here
![изображение](https://github.com/jalan/pdftotext/assets/69252550/48ef601a-2e3f-4e37-9632-dbc6acf00312)

How i can get rid of this strange text?

**Comment by jalan** [comment]
Can you provide a link to the PDF in question?

**Comment by Wowhere** [comment]
Sorry for delay. PDF is here https://drive.google.com/file/d/1zf9gJ18SKwEEJnTl-O-CDfdz09ZOcSq5/view?usp=sharing

**Comment by Wowhere** [comment]
How i can set custom font for pdftotext?

**Comment by jalan** [comment]
It sounds haven't made the effort to understand the issue.

There is no fix for us to do here. The creator of that PDF has made it so you can't automatically extract the correct text.
