### ISSUE TITLE
Poppler/error seen while extracting text from PDF such as poppler/error (572194): Unknown filter 'JPXDecode'\n

### ISSUE THREAD

**Issue by AsfarHorani** [jalan/pdftotext#116]
HI I am seeing alot of errors while using Pdftotext to extract text from given pdfs. Some of the errors are given below, not sure if its related to python environment or poppler. I am using pdftotext version 2.1.6:

- poppler/error: Invalid Font Weight
- poppler/error: Missing language pack for 'Adobe-CNS1' mapping
- poppler/error: Expected the default config, but wasn't able to find it, or it isn't a Dictionary

**Comment by jalan** [comment]
> from given pdfs

Can you link or attach the PDFs?

**Comment by jalan** [comment]
No response
