### ISSUE TITLE
Can't make crop work

### ISSUE THREAD

**Issue by iconoclasthero** [jalan/pdftotext#119]
Have a .pdf that has pages with a header I want to remove.
I tried `$ rm *txt; pdftotext -f 5 -x 0 -W -1 -y 3500 -H -1 file.pdf 2>/dev/null; cat *txt|more`
and it did not give me any cropping regardless of the -y value.

Also, the 2>/dev/null is in there because it prints "`Syntax Warning (1283779): Badly formatted number`" 3550 times (based on running with `2>&1 > /dev/null|wc -l`)

**Comment by jalan** [comment]
This is a python library. It looks like you're using a CLI from https://gitlab.freedesktop.org/poppler/poppler
