### ISSUE TITLE
Installing and working with anaconda

### ISSUE THREAD

**Issue by lohithn4** [jalan/pdftotext#12]
Hi,
please add the following code for python-anaconda part, otherwise it results in errors while importing pdftotext in jupyter notebook

`conda install libgcc`

Thanks for yours library, it works very good and does the job perfectly.

**Comment by jalan** [comment]
Thanks for the report!

I'm not familiar with anaconda? conda? miniconda? Sounds like I need to give it a try sometime and then add some guidance to the README.

I'll leave this issue open for now, so other anaconda users might find it.

**Comment by jalan** [comment]
@lohithn4 What OS is this and what version of anaconda? I have a fresh install of anaconda2 5.2.0 on macOS here and don't experience this issue. libgcc seems to be shipped with anaconda.

Anaconda seems to use strange build settings in general, at least on macOS, so I wouldn't be surprised if there is something here I need to fix. See #22 for some related details.

**Comment by jalan** [comment]
Closing for lack of current information. Everything looks good to me here, but if anyone has more info, please reopen.

**Comment by thesunkid19** [comment]
Hey @lohithn4, thank you for your report. It helps me a lot!
I've posed an issue in the following topic: https://github.com/jalan/pdftotext/issues/23#issuecomment-454652820 . After trying more way proposed in `Issues` area, I end up here and it fixed my bug.

**Comment by jalan** [comment]
@thesunkid19 Thanks for confirming that there's still an issue here. How did you install Conda? I thought Anaconda already came with libgcc, but maybe Miniconda doesn't? If that's the issue, I will add a note to the README about it.

**Comment by jalan** [comment]
I finally added a note to the README about this
