### ISSUE TITLE
pdftotext.Error: Poppler error creating document

### ISSUE THREAD

**Issue by prakritidev** [jalan/pdftotext#17]
while using pdftotext with multiprocessing module on ec2
```
('read pdf file', '1004.5293.pdf')
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    result = pool.map(pdf_extract, filenames)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
pdftotext.Error: Poppler error creating document
```

My code: 

```
def pdf_extract(dirs):
    paths, filename = dirs
    file = filename.replace(".pdf", ".txt")
    if file in have:
        print("file alreafy extracted!!")
    else:
	print("read pdf file", filename)
        with open(os.path.join(paths, filename), "rb") as f:
            pdf = pdftotext.PDF(f)
            prin(len(pdf))
        text = "\n\n".join(pdf)
        print("converted file")
        file = filename.replace(".pdf", ".txt")
        with open(txt_path+file, "w") as f:
            f.writelines(text)
            f.close()
            print("saved file")
        time.sleep(0.01)
```
Link : [arxiv paper](https://arxiv.org/pdf/1004.5293.pdf)

**Comment by jalan** [comment]
Can you attach the PDF in question, `1004.5293.pdf`?

**Comment by jalan** [comment]
Okay, I found it. Works fine here:

```
>>> import pdftotext
>>> f = open("1004.5293.pdf", "rb")
>>> pdf = pdftotext.PDF(f)
>>> len(pdf)
34
```

What version of poppler do you have?

**Comment by prakritidev** [comment]
I'm using Version: 3:4.8.5-1

**Comment by jalan** [comment]
`3:4.8.5-1` doesn't look like a poppler version. It should look something like `0.63.0`. You can see some common versions at [poppler.freedesktop.org](https://poppler.freedesktop.org/) under the Packaged Versions section.

Your code looks fine to me, but if you're using an older version of poppler, errors like this are more common.

**Comment by arl170330** [comment]
how do I install poppler on windows? After I download a zip, which directory it needs to be placed at.

**Comment by bhakti-visotrust** [comment]
I'm getting this error when running `pdftotext.PDF(f)` on AWS Lambda (Linux) but it works successfully with the same document when running on MacOS.

**Comment by AlexisH** [comment]
I'm getting this error too when running `pdftotext.PDF(f)` on Ubuntu 20.04.5 LTS. Was working fine last month. No code change.
I upgraded the pdftotext package from 2.1.5 to 2.2.2 but the issue is still there.

**Comment by dvtate** [comment]
Same issue with same file, Arch Linux poppler 23.12.0-1 and pdftotext 2.2.2-4
