### ISSUE TITLE
No additional option to ignore header and footer text

### ISSUE THREAD

**Issue by ilamparithi10** [jalan/pdftotext#31]
Is there any option to ignore the contents of header and footer text while extracting?

**Comment by jalan** [comment]
As far as I know, PDFs don't generally have a concept of header and footer. A few PDFs might use tagging to mark pagination artifacts, but they seem to be rare. I just tested all the PDFs I happen to have on my local machine, from various sources, and not even one of them are tagged.

**Comment by ahmed-bhs** [comment]
@jalan is there a way the to ise the opmargin option ?
