### ISSUE TITLE
Bounding boxes

### ISSUE THREAD

**Issue by Immortalin** [jalan/pdftotext#32]
The poppler command line `pdftotext` to has a layout option allowing specific extraction based on bounding boxes. Can that feature be integrated into this?

**Comment by jeanmonet** [comment]
I am also interested in this feature, and would help implement, but I'm not familiar enough with C. The poppler command line [does have many possible arguments](http://manpages.ubuntu.com/manpages/eoan/en/man1/pdftotext.1.html), and it would be nice to be able to implement them with this Python wrapper.

My usage case is to be able to extract text correctly from PDFs with multiple columns per page (ie like new papers), where layout is important.

**Comment by jalan** [comment]
Closing this one since it is discussed in more detail in #66
