### ISSUE TITLE
Unknown symbols found in scientific literature

### ISSUE THREAD

**Issue by jadeshi** [jalan/pdftotext#38]
Hi,
I'm trying to convert a PDF from a scientific journal to a text file, but many of the characters such as the "~" sign and Greek symbols do not get read/converted correctly. For example:

Original text:
<img width="353" alt="Screen Shot 2019-04-17 at 12 40 19 PM" src="https://user-images.githubusercontent.com/3607034/56315988-0bfbd280-610e-11e9-95cd-5c855e10758b.png">

Converted text:
<img width="304" alt="Screen Shot 2019-04-17 at 12 39 50 PM" src="https://user-images.githubusercontent.com/3607034/56316017-1f0ea280-610e-11e9-94db-35b84ab46413.png">

 Is there a straightforward fix for this?

Thanks!

**Comment by jalan** [comment]
I would bet that this is similar to #25. Can you attach the PDF in question or post a link to it, so I can have a look?

**Comment by jadeshi** [comment]
Ah, yes it was indeed an issue with specialized fonts. Thanks!
