### ISSUE TITLE
Extract text line by line

### ISSUE THREAD

**Issue by vlall** [jalan/pdftotext#39]
Is there a way to extract text line-by-line instead of page-by-page. There aren't helpful `\n`'s in the code for this. I guess I could always just create a new line every set number of characters. Just wondering if this is a built-in feature.

**Comment by vlall** [comment]
Actually there are new lines in the text, this is solved.

**Comment by laris** [comment]
@vlall Could i ask you how you read one page then read line-by-line?
I also need to process one page line-by-line but the build-in function only have print(pdf[page-id]).

Thanks

**Comment by jalan** [comment]
@laris You can use the [str.splitlines function](https://docs.python.org/3/library/stdtypes.html#str.splitlines) to do that. For example, to read the first page line-by-line:

```python

page = pdf[0]
for line in page.splitlines():
    print(line)  # Or do whatever you want with the line instead of printing it
```

**Comment by laris** [comment]
> @laris You can use the [str.splitlines function](https://docs.python.org/3/library/stdtypes.html#str.splitlines) to do that. For example, to read the first page line-by-line:
> 
> ```python
> page = pdf[0]
> for line in page.splitlines():
>     print(line)  # Or do whatever you want with the line instead of printing it
> ```

Thank you @jalan , sorry I'm new to learn py.
