### ISSUE TITLE
Is it possible to get coordinates of bounding boxes of each word of the text?

### ISSUE THREAD

**Issue by MartinThoma** [jalan/pdftotext#4]
I would like to highlight parts of the PDF. Is it possible to get bounding boxes for each word in the PDF?

**Comment by jalan** [comment]
I'm afraid that's outside the scope of this project. I believe poppler itself does have that functionality, but not in the interface library used here (poppler-cpp).

**Comment by RahulBadenkal** [comment]
@MartinThoma Even I have the same requirement of highlighting parts of pdf. How you found any solution?

**Comment by MartinThoma** [comment]
> Have you found any solution?

No.

I don't completely remember. I think I side-passed the problem, rendering it to HTML and then highlighting or using the browser in some other way.
