### ISSUE TITLE
Error installing pdftotext

### ISSUE THREAD

**Issue by MiaHuang97** [jalan/pdftotext#41]
Collecting pdftotext
  Using cached https://files.pythonhosted.org/packages/21/35/60094dbadd9de2035873390b1cac25e01da605844eba6a07a53a82fa4adc/pdftotext-2.1.1.tar.gz
Building wheels for collected packages: pdftotext
  Building wheel for pdftotext (setup.py): started
  Building wheel for pdftotext (setup.py): finished with status 'error'
  Complete output from command C:\Users\huang\AppData\Local\Continuum\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\huang\\AppData\\Local\\Temp\\pip-install-amj4lgms\\pdftotext\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\huang\AppData\Local\Temp\pip-wheel-suicv9j_ --python-tag cp37:
  WARNING: pkg-config not found--guessing at poppler version.
           If the build fails, install pkg-config and try again.
  running bdist_wheel
  running build
  running build_ext
  building 'pdftotext' extension
  creating build
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPOPPLER_CPP_AT_LEAST_0_30_0=1 -IC:\Users\huang\AppData\Local\Continuum\anaconda3\include -IC:\Users\huang\AppData\Local\Continuum\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tppdftotext.cpp /Fobuild\temp.win-amd64-3.7\Release\pdftotext.obj -Wall
  pdftotext.cpp
  C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt_io.h(49): warning C4820: '_finddata32i64_t': '4' bytes padding added after data member '_finddata32i64_t::name'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt_io.h(54): warning C4820: '_finddata64i32_t': '4' bytes padding added after data member '_finddata64i32_t::attrib'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt_io.h(64): warning C4820: '__finddata64_t': '4' bytes padding added after data member '__finddata64_t::attrib'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt_io.h(69): warning C4820: '__finddata64_t': '4' bytes padding added after data member '__finddata64_t::name'
  C:\Program Files (x86)\Windows Kits\8.1\include\shared\basetsd.h(418): warning C4668: '_WIN32_WINNT' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\time.h(35): warning C4820: '_timespec64': '4' bytes padding added after data member '_timespec64::tv_nsec'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\time.h(42): warning C4820: 'timespec': '4' bytes padding added after data member 'timespec::tv_nsec'
  c:\users\huang\appdata\local\continuum\anaconda3\include\object.h(381): warning C4820: '_typeobject': '4' bytes padding added after data member '_typeobject::tp_flags'
  c:\users\huang\appdata\local\continuum\anaconda3\include\object.h(425): warning C4820: '_typeobject': '4' bytes padding added after data member '_typeobject::tp_version_tag'
  c:\users\huang\appdata\local\continuum\anaconda3\include\object.h(440): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::slot'
  c:\users\huang\appdata\local\continuum\anaconda3\include\object.h(448): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::flags'
  c:\users\huang\appdata\local\continuum\anaconda3\include\bytearrayobject.h(30): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::ob_exports'
  c:\users\huang\appdata\local\continuum\anaconda3\include\bytesobject.h(41): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::ob_sval'
  c:\users\huang\appdata\local\continuum\anaconda3\include\bytesobject.h(165): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::small_buffer'
  c:\users\huang\appdata\local\continuum\anaconda3\include\unicodeobject.h(330): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::state'
  c:\users\huang\appdata\local\continuum\anaconda3\include\unicodeobject.h(905): warning C4820: '<unnamed-tag>': '2' bytes padding added after data member '<unnamed-tag>::readonly'
  c:\users\huang\appdata\local\continuum\anaconda3\include\longintrepr.h(88): warning C4820: '_longobject': '4' bytes padding added after data member '_longobject::ob_digit'
  c:\users\huang\appdata\local\continuum\anaconda3\include\memoryobject.h(45): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::flags'
  c:\users\huang\appdata\local\continuum\anaconda3\include\memoryobject.h(62): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::flags'
  c:\users\huang\appdata\local\continuum\anaconda3\include\methodobject.h(61): warning C4820: 'PyMethodDef': '4' bytes padding added after data member 'PyMethodDef::ml_flags'
  c:\users\huang\appdata\local\continuum\anaconda3\include\moduleobject.h(62): warning C4820: 'PyModuleDef_Slot': '4' bytes padding added after data member 'PyModuleDef_Slot::slot'
  c:\users\huang\appdata\local\continuum\anaconda3\include\pystate.h(48): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::utf8_mode'
  c:\users\huang\appdata\local\continuum\anaconda3\include\pystate.h(51): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::argc'
  c:\users\huang\appdata\local\continuum\anaconda3\include\pystate.h(55): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::nxoption'
  c:\users\huang\appdata\local\continuum\anaconda3\include\pystate.h(58): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::nwarnoption'
  c:\users\huang\appdata\local\continuum\anaconda3\include\pystate.h(68): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::nmodule_search_path'
  c:\users\huang\appdata\local\continuum\anaconda3\include\pystate.h(77): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::_disable_importlib'
  c:\users\huang\appdata\local\continuum\anaconda3\include\pystate.h(98): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::install_signal_handlers'
  c:\users\huang\appdata\local\continuum\anaconda3\include\pystate.h(225): warning C4820: '_ts': '2' bytes padding added after data member '_ts::recursion_critical'
  c:\users\huang\appdata\local\continuum\anaconda3\include\pystate.h(233): warning C4820: '_ts': '4' bytes padding added after data member '_ts::use_tracing'
  c:\users\huang\appdata\local\continuum\anaconda3\include\pystate.h(256): warning C4820: '_ts': '4' bytes padding added after data member '_ts::gilstate_counter'
  c:\users\huang\appdata\local\continuum\anaconda3\include\pystate.h(290): warning C4820: '_ts': '4' bytes padding added after data member '_ts::coroutine_origin_tracking_depth'
  c:\users\huang\appdata\local\continuum\anaconda3\include\pystate.h(293): warning C4820: '_ts': '4' bytes padding added after data member '_ts::in_coroutine_wrapper'
  c:\users\huang\appdata\local\continuum\anaconda3\include\genobject.h(33): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::gi_running'
  c:\users\huang\appdata\local\continuum\anaconda3\include\genobject.h(53): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::cr_running'
  c:\users\huang\appdata\local\continuum\anaconda3\include\genobject.h(70): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::ag_running'
  c:\users\huang\appdata\local\continuum\anaconda3\include\descrobject.h(29): warning C4820: 'wrapperbase': '4' bytes padding added after data member 'wrapperbase::offset'
  c:\users\huang\appdata\local\continuum\anaconda3\include\descrobject.h(33): warning C4820: 'wrapperbase': '4' bytes padding added after data member 'wrapperbase::flags'
  c:\users\huang\appdata\local\continuum\anaconda3\include\structseq.h(20): warning C4820: 'PyStructSequence_Desc': '4' bytes padding added after data member 'PyStructSequence_Desc::n_in_sequence'
  c:\users\huang\appdata\local\continuum\anaconda3\include\pyerrors.h(18): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
  c:\users\huang\appdata\local\continuum\anaconda3\include\pyerrors.h(22): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
  c:\users\huang\appdata\local\continuum\anaconda3\include\pyerrors.h(32): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
  c:\users\huang\appdata\local\continuum\anaconda3\include\pyerrors.h(39): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
  c:\users\huang\appdata\local\continuum\anaconda3\include\pyerrors.h(48): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
  c:\users\huang\appdata\local\continuum\anaconda3\include\pyerrors.h(53): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
  c:\users\huang\appdata\local\continuum\anaconda3\include\pyerrors.h(65): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
  c:\users\huang\appdata\local\continuum\anaconda3\include\modsupport.h(90): warning C4820: '_PyArg_Parser': '4' bytes padding added after data member '_PyArg_Parser::max'
  c:\users\huang\appdata\local\continuum\anaconda3\include\pylifecycle.h(15): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::user_err'
  c:\users\huang\appdata\local\continuum\anaconda3\include\import.h(140): warning C4820: '_frozen': '4' bytes padding added after data member '_frozen::size'
  c:\users\huang\appdata\local\continuum\anaconda3\include\fileutils.h(79): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member '_Py_stat_struct::st_dev'
  c:\users\huang\appdata\local\continuum\anaconda3\include\fileutils.h(81): warning C4820: '_Py_stat_struct': '2' bytes padding added after data member '_Py_stat_struct::st_mode'
  c:\users\huang\appdata\local\continuum\anaconda3\include\fileutils.h(85): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member '_Py_stat_struct::st_rdev'
  c:\users\huang\appdata\local\continuum\anaconda3\include\fileutils.h(88): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member '_Py_stat_struct::st_atime_nsec'
  c:\users\huang\appdata\local\continuum\anaconda3\include\fileutils.h(90): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member '_Py_stat_struct::st_mtime_nsec'
  pdftotext.cpp(3): fatal error C1083: Cannot open include file: 'poppler/cpp/poppler-document.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
  
  ----------------------------------------
  Running setup.py clean for pdftotext
Failed to build pdftotext
Installing collected packages: pdftotext
  Running setup.py install for pdftotext: started
    Running setup.py install for pdftotext: finished with status 'error'
    Complete output from command C:\Users\huang\AppData\Local\Continuum\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\huang\\AppData\\Local\\Temp\\pip-install-amj4lgms\\pdftotext\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\huang\AppData\Local\Temp\pip-record-w5c0rhy9\install-record.txt --single-version-externally-managed --compile:
    WARNING: pkg-config not found--guessing at poppler version.
             If the build fails, install pkg-config and try again.
    running install
    running build
    running build_ext
    building 'pdftotext' extension
    creating build
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPOPPLER_CPP_AT_LEAST_0_30_0=1 -IC:\Users\huang\AppData\Local\Continuum\anaconda3\include -IC:\Users\huang\AppData\Local\Continuum\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tppdftotext.cpp /Fobuild\temp.win-amd64-3.7\Release\pdftotext.obj -Wall
    pdftotext.cpp
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt_io.h(49): warning C4820: '_finddata32i64_t': '4' bytes padding added after data member '_finddata32i64_t::name'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt_io.h(54): warning C4820: '_finddata64i32_t': '4' bytes padding added after data member '_finddata64i32_t::attrib'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt_io.h(64): warning C4820: '__finddata64_t': '4' bytes padding added after data member '__finddata64_t::attrib'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt_io.h(69): warning C4820: '__finddata64_t': '4' bytes padding added after data member '__finddata64_t::name'
    C:\Program Files (x86)\Windows Kits\8.1\include\shared\basetsd.h(418): warning C4668: '_WIN32_WINNT' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\time.h(35): warning C4820: '_timespec64': '4' bytes padding added after data member '_timespec64::tv_nsec'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\time.h(42): warning C4820: 'timespec': '4' bytes padding added after data member 'timespec::tv_nsec'
    c:\users\huang\appdata\local\continuum\anaconda3\include\object.h(381): warning C4820: '_typeobject': '4' bytes padding added after data member '_typeobject::tp_flags'
    c:\users\huang\appdata\local\continuum\anaconda3\include\object.h(425): warning C4820: '_typeobject': '4' bytes padding added after data member '_typeobject::tp_version_tag'
    c:\users\huang\appdata\local\continuum\anaconda3\include\object.h(440): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::slot'
    c:\users\huang\appdata\local\continuum\anaconda3\include\object.h(448): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::flags'
    c:\users\huang\appdata\local\continuum\anaconda3\include\bytearrayobject.h(30): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::ob_exports'
    c:\users\huang\appdata\local\continuum\anaconda3\include\bytesobject.h(41): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::ob_sval'
    c:\users\huang\appdata\local\continuum\anaconda3\include\bytesobject.h(165): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::small_buffer'
    c:\users\huang\appdata\local\continuum\anaconda3\include\unicodeobject.h(330): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::state'
    c:\users\huang\appdata\local\continuum\anaconda3\include\unicodeobject.h(905): warning C4820: '<unnamed-tag>': '2' bytes padding added after data member '<unnamed-tag>::readonly'
    c:\users\huang\appdata\local\continuum\anaconda3\include\longintrepr.h(88): warning C4820: '_longobject': '4' bytes padding added after data member '_longobject::ob_digit'
    c:\users\huang\appdata\local\continuum\anaconda3\include\memoryobject.h(45): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::flags'
    c:\users\huang\appdata\local\continuum\anaconda3\include\memoryobject.h(62): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::flags'
    c:\users\huang\appdata\local\continuum\anaconda3\include\methodobject.h(61): warning C4820: 'PyMethodDef': '4' bytes padding added after data member 'PyMethodDef::ml_flags'
    c:\users\huang\appdata\local\continuum\anaconda3\include\moduleobject.h(62): warning C4820: 'PyModuleDef_Slot': '4' bytes padding added after data member 'PyModuleDef_Slot::slot'
    c:\users\huang\appdata\local\continuum\anaconda3\include\pystate.h(48): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::utf8_mode'
    c:\users\huang\appdata\local\continuum\anaconda3\include\pystate.h(51): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::argc'
    c:\users\huang\appdata\local\continuum\anaconda3\include\pystate.h(55): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::nxoption'
    c:\users\huang\appdata\local\continuum\anaconda3\include\pystate.h(58): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::nwarnoption'
    c:\users\huang\appdata\local\continuum\anaconda3\include\pystate.h(68): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::nmodule_search_path'
    c:\users\huang\appdata\local\continuum\anaconda3\include\pystate.h(77): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::_disable_importlib'
    c:\users\huang\appdata\local\continuum\anaconda3\include\pystate.h(98): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::install_signal_handlers'
    c:\users\huang\appdata\local\continuum\anaconda3\include\pystate.h(225): warning C4820: '_ts': '2' bytes padding added after data member '_ts::recursion_critical'
    c:\users\huang\appdata\local\continuum\anaconda3\include\pystate.h(233): warning C4820: '_ts': '4' bytes padding added after data member '_ts::use_tracing'
    c:\users\huang\appdata\local\continuum\anaconda3\include\pystate.h(256): warning C4820: '_ts': '4' bytes padding added after data member '_ts::gilstate_counter'
    c:\users\huang\appdata\local\continuum\anaconda3\include\pystate.h(290): warning C4820: '_ts': '4' bytes padding added after data member '_ts::coroutine_origin_tracking_depth'
    c:\users\huang\appdata\local\continuum\anaconda3\include\pystate.h(293): warning C4820: '_ts': '4' bytes padding added after data member '_ts::in_coroutine_wrapper'
    c:\users\huang\appdata\local\continuum\anaconda3\include\genobject.h(33): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::gi_running'
    c:\users\huang\appdata\local\continuum\anaconda3\include\genobject.h(53): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::cr_running'
    c:\users\huang\appdata\local\continuum\anaconda3\include\genobject.h(70): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::ag_running'
    c:\users\huang\appdata\local\continuum\anaconda3\include\descrobject.h(29): warning C4820: 'wrapperbase': '4' bytes padding added after data member 'wrapperbase::offset'
    c:\users\huang\appdata\local\continuum\anaconda3\include\descrobject.h(33): warning C4820: 'wrapperbase': '4' bytes padding added after data member 'wrapperbase::flags'
    c:\users\huang\appdata\local\continuum\anaconda3\include\structseq.h(20): warning C4820: 'PyStructSequence_Desc': '4' bytes padding added after data member 'PyStructSequence_Desc::n_in_sequence'
    c:\users\huang\appdata\local\continuum\anaconda3\include\pyerrors.h(18): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
    c:\users\huang\appdata\local\continuum\anaconda3\include\pyerrors.h(22): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
    c:\users\huang\appdata\local\continuum\anaconda3\include\pyerrors.h(32): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
    c:\users\huang\appdata\local\continuum\anaconda3\include\pyerrors.h(39): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
    c:\users\huang\appdata\local\continuum\anaconda3\include\pyerrors.h(48): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
    c:\users\huang\appdata\local\continuum\anaconda3\include\pyerrors.h(53): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
    c:\users\huang\appdata\local\continuum\anaconda3\include\pyerrors.h(65): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
    c:\users\huang\appdata\local\continuum\anaconda3\include\modsupport.h(90): warning C4820: '_PyArg_Parser': '4' bytes padding added after data member '_PyArg_Parser::max'
    c:\users\huang\appdata\local\continuum\anaconda3\include\pylifecycle.h(15): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::user_err'
    c:\users\huang\appdata\local\continuum\anaconda3\include\import.h(140): warning C4820: '_frozen': '4' bytes padding added after data member '_frozen::size'
    c:\users\huang\appdata\local\continuum\anaconda3\include\fileutils.h(79): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member '_Py_stat_struct::st_dev'
    c:\users\huang\appdata\local\continuum\anaconda3\include\fileutils.h(81): warning C4820: '_Py_stat_struct': '2' bytes padding added after data member '_Py_stat_struct::st_mode'
    c:\users\huang\appdata\local\continuum\anaconda3\include\fileutils.h(85): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member '_Py_stat_struct::st_rdev'
    c:\users\huang\appdata\local\continuum\anaconda3\include\fileutils.h(88): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member '_Py_stat_struct::st_atime_nsec'
    c:\users\huang\appdata\local\continuum\anaconda3\include\fileutils.h(90): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member '_Py_stat_struct::st_mtime_nsec'
    pdftotext.cpp(3): fatal error C1083: Cannot open include file: 'poppler/cpp/poppler-document.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    
    ----------------------------------------
  Failed building wheel for pdftotext
Command "C:\Users\huang\AppData\Local\Continuum\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\huang\\AppData\\Local\\Temp\\pip-install-amj4lgms\\pdftotext\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\huang\AppData\Local\Temp\pip-record-w5c0rhy9\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\huang\AppData\Local\Temp\pip-install-amj4lgms\pdftotext\

**Comment by jalan** [comment]
Please see #16

**Comment by ADTC** [comment]
Just in case, someone else arrives here because they were trying to use [hxu296/nlp-resume-parser](https://github.com/hxu296/nlp-resume-parser): I'm on macOS, and I just had to install poppler as mentioned in the [readme of this project](https://github.com/jalan/pdftotext#readme) using Homebrew.

```sh
brew install pkg-config poppler python
```
