### ISSUE TITLE
Can't pip install on Mac 

### ISSUE THREAD

**Issue by R470R** [jalan/pdftotext#43]
hey, when I run the pip command it gives me the following error:
 ERROR: Could not find a version that satisfies the requirement pdftotext (from versions: none)
ERROR: No matching distribution found for pdftotext

is there another way to install it, or solve this way?

**Comment by jalan** [comment]
Can you provide more detail? What command did you type? What was the full output?

**Comment by R470R** [comment]
simply typed `pip install pdftotext` on terminal, and received the following error

> Owners-MacBook-Pro:~ owner$ pip install pdftotext
You are using pip version 6.1.1, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pdftotext
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(54, 'Connection reset by peer'))': /simple/pdftotext/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(54, 'Connection reset by peer'))': /simple/pdftotext/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(54, 'Connection reset by peer'))': /simple/pdftotext/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(54, 'Connection reset by peer'))': /simple/pdftotext/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(54, 'Connection reset by peer'))': /simple/pdftotext/
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(54, 'Connection reset by peer'))': /simple/pdftotext/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(54, 'Connection reset by peer'))': /simple/pdftotext/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(54, 'Connection reset by peer'))': /simple/pdftotext/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(54, 'Connection reset by peer'))': /simple/pdftotext/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(54, 'Connection reset by peer'))': /simple/pdftotext/
  Could not find a version that satisfies the requirement pdftotext (from versions: )
  No matching distribution found for pdftotext

**Comment by R470R** [comment]
already solved it , needed to disable ipv6 while using pip due to my wi-fi router I think

**Comment by jalan** [comment]
:+1:

**Comment by R470R** [comment]
Now I'm getting this error 

> Owners-MacBook-Pro:~ owner$ pip install pdftotext
You are using pip version 6.1.1, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pdftotext
  Using cached https://files.pythonhosted.org/packages/a6/a7/c202adb0bcd3adc3030b0c5f7f0e21f62a721913e93296e6c4ddc305cbd3/pdftotext-2.1.2.tar.gz
Installing collected packages: pdftotext
  Running setup.py install for pdftotext
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/vh/ktk4_qrn5k7_043z22q7y2p00000gn/T/pip-build-mzgEx9/pdftotext/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/vh/ktk4_qrn5k7_043z22q7y2p00000gn/T/pip-S6ghdk-record/install-record.txt --single-version-externally-managed --compile:
    /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_ext
    building 'pdftotext' extension
    creating build
    creating build/temp.macosx-10.14-intel-2.7
    cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -DPOPPLER_CPP_AT_LEAST_0_30_0=0 -I/usr/local/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pdftotext.cpp -o build/temp.macosx-10.14-intel-2.7/pdftotext.o -Wall -mmacosx-version-min=10.9
    pdftotext.cpp:3:10: fatal error: 'poppler/cpp/poppler-document.h' file not found
    #include <poppler/cpp/poppler-document.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    error: command 'cc' failed with exit status 1
    
    ----------------------------------------
    Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/vh/ktk4_qrn5k7_043z22q7y2p00000gn/T/pip-build-mzgEx9/pdftotext/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/vh/ktk4_qrn5k7_043z22q7y2p00000gn/T/pip-S6ghdk-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/vh/ktk4_qrn5k7_043z22q7y2p00000gn/T/pip-build-mzgEx9/pdftotext

**Comment by jalan** [comment]
Did you install the dependencies? `brew install pkg-config poppler` is the usual way to do it on macOS.

**Comment by vandelouw** [comment]
Hi @R470R, did you solve the problem ? I have the same issue...

**Comment by davydany** [comment]
Still having the same issue in 2022, on a M1 Macbook Pro. Anyone else have this issue? I tried all the things mentioned on this post.

**Comment by davydany** [comment]
Ping! It's March 14, 2024! Happy Pi Day! Has anyone figured out a way around this?
