### ISSUE TITLE
pip install fails due to missing headers if Homebrew is in a nonstandard location

### ISSUE THREAD

**Issue by bgshacklett** [jalan/pdftotext#44]
I have Homebrew is installed in a nonstandard location (`~/homebrew`). I've installed pkg-config and poppler, but when I run `pipenv install pdftotext`, the install fails with an error stating: "pdftotext.cpp:3:10: fatal error: 'poppler/cpp/poppler-document.h' file not found".

I see that `setup.py` is not looking in the path where the headers for poppler are installed on my machine. Pkg-config is able to find them, however:

```
pkg-config poppler-cpp  --cflags-only-I
-I/Users/brianshacklett/Applications/homebrew/Cellar/poppler/0.79.0/include/poppler/cpp -I/Users/brianshacklett/Applications/homebrew/Cellar/poppler/0.79.0/include/poppler
```

Perhaps something like the following might be added to help locate the include paths?
```python
import subprocess

def find_poppler_headers():
    try:
        with subprocess.Popen(
                                 [
                                     "pkg-config",
                                     "--cflags-only-I",
                                     "poppler-cpp",
                                 ],
                                 stdout=subprocess.PIPE,
                                 stderr=subprocess.PIPE,
                             ) as proc: 
            outs, errs = proc.communicate(timeout=1)

            print('')
            print('Outs: {}'.format(outs))
            print('')

        if errs:
            raise Exception(errs)

        poppler_include_paths = outs.decode('utf-8') \
                                    .replace('\n','') \
                                    .replace('-I/','/')\
                                    .split(' ')

        print((poppler_include_paths))

    except subprocess.CalledProcessError:
        return False
    except OSError:
        print("WARNING: pkg-config not found--guessing at poppler include path.")
        print("         If the build fails, install pkg-config and try again.")
    return True

include_dirs = find_poppler_headers()
```

**Comment by jalan** [comment]
Huh, I didn't know that homebrew supported installing to a custom location! Can you check if version 2.1.1 shows the same issue? `pip install pdftotext==2.1.1`

I'll take a look, but this will be difficult to test. I'm not about to blow up my own homebrew install now that I see [this](https://docs.brew.sh/Installation):

> However do yourself a favour and install to /usr/local. Some things may not build when installed elsewhere. One of the reasons Homebrew just works relative to the competition is because we recommend installing to /usr/local. Pick another prefix at your peril!

:fearful:

**Comment by jalan** [comment]
I think this is covered by #86
