### ISSUE TITLE
Program Stuck with a pdf

### ISSUE THREAD

**Issue by eladbitton** [jalan/pdftotext#46]
While extracting text from this pdf:
http://ihassociation.org/wordpress/wp-content/uploads/2015/06/2014-ASHP-Handbook-web-edition.pdf

The program just gets stuck.

Reproduce:

```python
import pdftotext

with open('./2014-ASHP-Handbook-web-edition.pdf', 'rb') as f:
    pdf = pdftotext.PDF(f)
text = "\n\n".join(pdf)
```

I tried to iterate through the pages and there is a specific page in which the program is stuck on.
The program is stuck and uses 100% cpu which means it keeps processing something.

If its a dependecies problem, adding timeout for processing would be good.

**Comment by jalan** [comment]
You can use the `multiprocessing` module to perform long-running tasks with a timeout. Here is a commented example script I called `readpdf.py`:

```python
import multiprocessing
import sys
import time

import pdftotext


def main():
    path = sys.argv[1]
    text = read_pdf(path)
    if text is None:
        sys.exit("timed out trying to read the PDF")
    print(text)


def read_pdf(path, timeout=5):
    # A queue to pass data between processes
    q = multiprocessing.Queue()

    # Start a new process
    p = multiprocessing.Process(target=read_pdf_process, args=(path, q,))
    p.start()

    # Wait some time for it to finish
    p.join(timeout=timeout)

    if p.is_alive():
        # The process is still running but we are out of time, so terminate it
        p.terminate()

    # Based on the exit code, either get the text that was extracted, or None
    # if we weren't able to finish
    p.join()
    if p.exitcode == 0:
        text = q.get()
    else:
        text = None

    q.close()
    return text


def read_pdf_process(path, q):
    with open(path, "rb") as f:
        pdf = pdftotext.PDF(f)
    text = "\n\n".join(pdf)
    q.put(text)
    q.close()


if __name__ == "__main__":
    main()
```

On a typical PDF, you get the text:
```
$ python readpdf.py abcde.pdf 
abcde.
```

On your troublesome PDF it will time out after five seconds:
```
$ python readpdf.py 2014-ASHP-Handbook-web-edition.pdf 
timed out trying to read the PDF
```

I hope it helps.

**Comment by jalan** [comment]
Closing, since this is something you should solve in your own code. I shouldn't change this module itself to do this on my side, since spinning up another process would be expensive and surprising to most users.
