### ISSUE TITLE
Unable to install poppler-cpp-devel and python-devel on RHEL 8

### ISSUE THREAD

**Issue by merismsk** [jalan/pdftotext#49]
Hi Jalan
As per official documentation on pdftotext webpage below libraries are required to be installed on REDHAT.
sudo yum install gcc-c++ pkgconfig poppler-cpp-devel python-devel redhat-rpm-config

Unfortunately i was unable to install poppler-cpp-devel and python-devel  and received below message:
sudo yum install poppler-cpp-devel python-devel
Red Hat Update Infrastructure 3 Client Configur 7.4 kB/s | 2.1 kB     00:00
Red Hat Enterprise Linux 8 for x86_64 - AppStre 8.1 kB/s | 2.8 kB     00:00
Red Hat Enterprise Linux 8 for x86_64 - BaseOS  7.5 kB/s | 2.3 kB     00:00
No match for argument: poppler-cpp-devel
No match for argument: python-devel
Error: Unable to find a match

I tried to install poppler from it's official linux webpage which is given below and went recursively and installed almost 10 dependencies such as cmake, libarchieve, fontconfig and the list went on.
http://www.linuxfromscratch.org/blfs/view/svn/general/poppler.html

Finally i have come to a stage where getting below error while installing pdftotext through pip3.
pip3 install pdftotext
creating build/lib.linux-x86_64-3.6
g++ -pthread -shared -Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redh                                                                             at-hardened-ld -g build/temp.linux-x86_64-3.6/pdftotext.o -L/usr/lib64 -lpoppler                                                                             -cpp -lpython3.6m -o build/lib.linux-x86_64-3.6/pdftotext.cpython-36m-x86_64-lin                                                                             ux-gnu.so
    /usr/bin/ld: cannot find -lpoppler-cpp
    collect2: error: ld returned 1 exit status
    error: command 'g++' failed with exit status 1

I am unable to understand above error and don't know how many more will be faced as i am working on same from 5 days.
It would be great if you can provide the libraries which are required for pdftotext and can be installed on REDHAT directly or without causing much errors.
We will be really grateful for your response.

**Comment by jalan** [comment]
`-devel` packages in RHEL 8 are part of the `codeready-builder` repo, which it looks like is enabled via

```
sudo subscription-manager repos --enable codeready-builder-for-rhel-8-x86_64-rpms
```

I think in RHEL 8 they don't have plain `python` packages anymore, so you will have to specify `python2-devel` or `python3-devel` depending on what you want.

Note that if you manually installed a bunch of packages from source as root, it is possible that you have messed up your system, and you may have trouble installing packages or compiling software from here on.

**Comment by jalan** [comment]
Updated the README to specify `python3-devel` now
