### ISSUE TITLE
pip install fails on macOs 

### ISSUE THREAD

**Issue by vandelouw** [jalan/pdftotext#50]
Hi, 
I'm running on macOs and trying ton install pdftotext
I tried 
`pip install pdftotext`
and got this error

> `Collecting pdftotext
>   Using cached https://files.pythonhosted.org/packages/a6/a7/c202adb0bcd3adc3030b0c5f7f0e21f62a721913e93296e6c4ddc305cbd3/pdftotext-2.1.2.tar.gz
> Building wheels for collected packages: pdftotext
>   Building wheel for pdftotext (setup.py) ... error
>   ERROR: Command errored out with exit status 1:
>    command: /Users/romainvandelouw/venv/oreilly/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zg/8mfp262s1093qtv0klghbfnr0000gn/T/pip-install-oailros8/pdftotext/setup.py'"'"'; __file__='"'"'/private/var/folders/zg/8mfp262s1093qtv0klghbfnr0000gn/T/pip-install-oailros8/pdftotext/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/zg/8mfp262s1093qtv0klghbfnr0000gn/T/pip-wheel-yvlotdyb --python-tag cp36
>        cwd: /private/var/folders/zg/8mfp262s1093qtv0klghbfnr0000gn/T/pip-install-oailros8/pdftotext/
>   Complete output (27 lines):
>   running bdist_wheel
>   running build
>   running build_ext
>   building 'pdftotext' extension
>   creating build
>   creating build/temp.macosx-10.7-x86_64-3.6
>   gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/romainvandelouw/anaconda/include -arch x86_64 -I/Users/romainvandelouw/anaconda/include -arch x86_64 -DPOPPLER_CPP_AT_LEAST_0_30_0=1 -I/usr/local/include -I/Users/romainvandelouw/anaconda/include/python3.6m -c pdftotext.cpp -o build/temp.macosx-10.7-x86_64-3.6/pdftotext.o -Wall -mmacosx-version-min=10.9
>   In file included from pdftotext.cpp:5:
>   /Users/romainvandelouw/anaconda/include/poppler/cpp/poppler-page.h:37:22: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
>       text_box(text_box&&) = default;
>                        ^
>   /Users/romainvandelouw/anaconda/include/poppler/cpp/poppler-page.h:37:28: warning: defaulted function definitions are a C++11 extension [-Wc++11-extensions]
>       text_box(text_box&&) = default;
>                              ^
>   /Users/romainvandelouw/anaconda/include/poppler/cpp/poppler-page.h:38:33: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
>       text_box& operator=(text_box&&) = default;
>                                   ^
>   /Users/romainvandelouw/anaconda/include/poppler/cpp/poppler-page.h:38:39: warning: defaulted function definitions are a C++11 extension [-Wc++11-extensions]
>       text_box& operator=(text_box&&) = default;
>                                         ^
>   4 warnings generated.
>   creating build/lib.macosx-10.7-x86_64-3.6
>   g++ -bundle -undefined dynamic_lookup -L/Users/romainvandelouw/anaconda/lib -arch x86_64 -L/Users/romainvandelouw/anaconda/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.6/pdftotext.o -L/usr/local/lib -lpoppler-cpp -o build/lib.macosx-10.7-x86_64-3.6/pdftotext.cpython-36m-darwin.so
>   clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
>   ld: library not found for -lstdc++
>   clang: error: linker command failed with exit code 1 (use -v to see invocation)
>   error: command 'g++' failed with exit status 1
>   ----------------------------------------
>   ERROR: Failed building wheel for pdftotext`

I read in previous issues that it could be related to dependencies but Popler is installed

`Warning: pkg-config 0.29.2 is already installed and up-to-date
To reinstall 0.29.2, run `brew reinstall pkg-config`
Warning: poppler 0.81.0 is already installed and up-to-date
To reinstall 0.81.0, run `brew reinstall poppler`

I read #26 but in my case it doesn't work outside the virtualenv either...

[verbose_pdftotext.txt](https://github.com/jalan/pdftotext/files/3927071/verbose_pdftotext.txt)
 is the result of `pip --verbose install pdftotext` : 

What am I missing ?
Thanks for your help !

**Comment by alnew** [comment]
+1 on this. Using Mojave 10.14.6

**Comment by vandelouw** [comment]
It seems the problem comes from the libstdc++ library which is used instead of libc++,
should something like 
`if platform.system() == "Darwin":
        # or gcc5?
        ext_args['extra_compile_args'].append("-stdlib=libc++")` 
work ?

**Comment by jalan** [comment]
It looks like you are using Anaconda, which is known to set up weird build environments. Did you try `conda install libgcc` as suggested in the README?

**Comment by vandelouw** [comment]
Hi Jalan,
thanks for your answer !
I tried but it didn't work, so I removed anaconda, and here is the result I get now

> Collecting pdftotext
  Using cached https://files.pythonhosted.org/packages/a6/a7/c202adb0bcd3adc3030b0c5f7f0e21f62a721913e93296e6c4ddc305cbd3/pdftotext-2.1.2.tar.gz
Building wheels for collected packages: pdftotext
  Building wheel for pdftotext (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/romainvandelouw/venv/ocr/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zg/8mfp262s1093qtv0klghbfnr0000gn/T/pip-install-5qmzym2i/pdftotext/setup.py'"'"'; __file__='"'"'/private/var/folders/zg/8mfp262s1093qtv0klghbfnr0000gn/T/pip-install-5qmzym2i/pdftotext/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/zg/8mfp262s1093qtv0klghbfnr0000gn/T/pip-wheel-ie81a4hm --python-tag cp36
       cwd: /private/var/folders/zg/8mfp262s1093qtv0klghbfnr0000gn/T/pip-install-5qmzym2i/pdftotext/
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'pdftotext' extension
  creating build
  creating build/temp.macosx-10.6-intel-3.6
  /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -DPOPPLER_CPP_AT_LEAST_0_30_0=1 -I/usr/local/include -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pdftotext.cpp -o build/temp.macosx-10.6-intel-3.6/pdftotext.o -Wall -mmacosx-version-min=10.9
  In file included from pdftotext.cpp:5:
  /usr/local/include/poppler/cpp/poppler-page.h:39:22: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
      text_box(text_box&&);
                       ^
  /usr/local/include/poppler/cpp/poppler-page.h:40:33: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
      text_box& operator=(text_box&&);
                                  ^
  2 warnings generated.
  In file included from pdftotext.cpp:5:
  /usr/local/include/poppler/cpp/poppler-page.h:39:22: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
      text_box(text_box&&);
                       ^
  /usr/local/include/poppler/cpp/poppler-page.h:40:33: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
      text_box& operator=(text_box&&);
                                  ^
  2 warnings generated.
  creating build/lib.macosx-10.6-intel-3.6
  /usr/bin/clang++ -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g build/temp.macosx-10.6-intel-3.6/pdftotext.o -L/usr/local/lib -lpoppler-cpp -o build/lib.macosx-10.6-intel-3.6/pdftotext.cpython-36m-darwin.so
  clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
  clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
  ld: library not found for -lstdc++
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  error: command '/usr/bin/clang++' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pdftotext

That's why I think the problem comes from the lstdc++ library, but I'm not sure and don't know how to fix it ?

**Comment by jalan** [comment]
@vandelouw Thanks for following up. This macOS build stuff is confusing. Nowhere am I asking for `libstdc++`, so I'm not sure where it's coming from. I wonder if I should try to force `libc++` on macOS all the time? Unfortunately I don't have a mac around to do any testing, so I risk breaking people's builds :grimacing:

**Comment by vandelouw** [comment]
And do you think it would be possible trying it for mac + Mojave 10.14.5 / Mojave 10.14.6 ?
There seems to be at least one other user having the same problem with this configuration, but I don't know if it's working for others... otherwise do you see something I could try ?

**Comment by gyermolenko** [comment]
I've encountered similar issue (`pip install pdftotext` fails on macos mojave)
but w/o mentions `libstdc`. Smth related to C syntax
```
    In file included from pdftotext.cpp:5:
    /usr/local/include/poppler/cpp/poppler-page.h:39:22: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
        text_box(text_box&&) noexcept;
                         ^
    /usr/local/include/poppler/cpp/poppler-page.h:39:25: error: expected ';' at end of declaration list
        text_box(text_box&&) noexcept;
                            ^
```

fixed with 
```$ CPPFLAGS="-std=c++11" pip install pdftotext```

**Comment by vandelouw** [comment]
Hi @gyermolenko,
thanks for the tip, I tried, and I also tried `sudo chown -R $(whoami) $(brew --prefix)/*` which seems to have worked for someone but what I get now is 
` pdftotext.cpp:3:10: fatal error: 'poppler/cpp/poppler-document.h' file not found
    #include <poppler/cpp/poppler-document.h>`....

**Comment by topoMole** [comment]
I'm having a similar issue on macOS Catalina 10.15.2 when trying to install via pip (no conda)

    In file included from pdftotext.cpp:5:
    /usr/local/include/poppler/cpp/poppler-page.h:39:22: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
        text_box(text_box&&) noexcept;
                         ^
    /usr/local/include/poppler/cpp/poppler-page.h:39:25: error: expected ';' at end of declaration list
        text_box(text_box&&) noexcept;
                            ^
                            ;
    /usr/local/include/poppler/cpp/poppler-page.h:40:33: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
        text_box& operator=(text_box&&) noexcept;
                                    ^
    /usr/local/include/poppler/cpp/poppler-page.h:40:36: error: expected ';' at end of declaration list
        text_box& operator=(text_box&&) noexcept;
                                       ^
                                       ;
    2 warnings and 2 errors generated.
    error: command 'xcrun' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-xzeuee1e/pdftotext/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-xzeuee1e/pdftotext/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-0aeh2b1f/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by jalan** [comment]
This should now be fixed in [version 2.1.4](https://pypi.org/project/pdftotext/2.1.4/)

**Comment by Git4Manohar** [comment]
I'm getting the same issue in MacOs Catalina 
`CPPFLAGS="-std=c++11" pip install pdftotext` didn't work for me

**Comment by ruddra** [comment]
Make sure your poppler is linked. Check using `brew install -s poppler`.

**Comment by erolhoke** [comment]
I am having the same issue and I checked and my poppler is totally up to date and linked.

**Comment by yonnym** [comment]
ARCHFLAGS="-arch x86_64" CC=clang CXX=clang++ pip install pdftotext works

**Comment by henrijaeger** [comment]
`ARCHFLAGS="-arch arm64" pip install pdftotext --compile --no-cache-dir` worked for me

Modified [this solution](https://stackoverflow.com/questions/72920577/mach-o-file-but-is-an-incompatible-architecture-have-arm64-need-x86-64) on GitHub
