### ISSUE TITLE
ImportError:  pdftotext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN7poppler8document6unlockERKSsS2_

### ISSUE THREAD

**Issue by wuxiaobo** [jalan/pdftotext#51]
python3.7 ，pdftotext isinstall sucess but 
import pdftotext 
>>> import pdftotext
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /root/anaconda3/lib/python3.7/site-packages/pdftotext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN7poppler8document6unlockERKSsS2_

**Comment by wuxiaobo** [comment]
conda list some is :
pcre                      8.43                 he6710b0_0  
pdftotext                 2.1.2                    pypi_0    pypi
pep8                      1.7.1                    py37_0  
pexpect                   4.6.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    5.4.1            py37h34e0f95_0  
pip                       19.0.3                   py37_0  
pixman                    0.38.0               h7b6447c_0  
pkginfo                   1.5.0.1                  py37_0  
plac                      0.9.6                    pypi_0    pypi
pluggy                    0.9.0                    py37_0  
ply                       3.11                     py37_0  
poppler                   0.65.0               h581218d_1  
poppler-data              0.4.9                         1    conda-forge
preshed                   1.0.1                    pypi_0    pypi
prometheus_client         0.6.0                    py37_0  
prompt_toolkit            2.0.9                    py37_0  
psutil                    5.6.1            py37h7b6447c_0  
ptyprocess                0.6.0                    py37_0  
py                        1.8.0                    py37_0  
py-lief                   0.9.0            py37h7725739_2

**Comment by samscudder** [comment]
I'm having the same problem on CentOS 7. Did you manage to work around this?

**Comment by raghavjajodia** [comment]
Hi, I am having the same issue. Can someone please let me know the solution?

**Comment by wuxiaobo** [comment]
no fixes to this problem

**Comment by jalan** [comment]
This is most likely an installation error. Nothing to fix here
