### ISSUE TITLE
Stop using `python setup.py test`

### ISSUE THREAD

**Issue by jalan** [jalan/pdftotext#57]
`python setup.py test` now results in a deprecation warning:

> WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.

Who knows when they will actually remove it :man_shrugging:

**Comment by stefan6419846** [comment]
Due to using only the stdlib *unittest* module, `python -m unittest discover --verbose --start-directory tests/` should be enough in theory.

**Comment by jalan** [comment]
Fixed, thanks to @stefan6419846 for the motivation :+1:
