### ISSUE TITLE
Inconsistent layout

### ISSUE THREAD

**Issue by Filip98** [jalan/pdftotext#59]
I'm not sure if this is pdftotext's intended use case as it does it's job fast but I guess it should be known.
I'm extracting this file:
https://nissrednjastrucna.edu.rs/data/documents/Opsti-deo.pdf
Which is in a consistent format

But I get a lot of this:
A)
B)
C)
line
line
line
or this
line
line
line
A)
B)
C)
or even better, one or several lines being in and the others out

**Comment by jalan** [comment]
The best I can offer is to try the extraction again with the `raw` option. It might help or it might not.

```python
pdf = pdftotext.PDF(f, raw=True)
```

PDF is a nasty format, so it is often very difficult to get the results you want. Sometimes you can get a reasonable result by rendering the PDF to an image and then using an OCR program to read text from that image.

**Comment by Filip98** [comment]
Truth be told I was using textract, only now did I try the raw program to try out the raw option and ... Without the raw option it produces very better results than I shown, like still inconsistent but something I can already scrap very easily...
```
90. ____________ is a circular junction where three or more roads join together and cars must drive around.
      а)   O-turn
     b)    Roundabout
      c)   Aboutround
     d)    Turnaround
```
Didn't need the Raw option, it kills the whitespace&newlines
This inconsistency likely happens because of the large distance between characters in the source file, I've consulted the guys at pdfminer and that was the culprit

So it's basically textract's fault, it produces what I mentioned in method="" or method="pdftotext"
I hear it does what you said in "tesseract" mode tho, converts the pdf to a ppm and then runs tesseract on it.
Thanks for your time and the great program
