### ISSUE TITLE
Installation raises error command "g++" failed with exit status 1

### ISSUE THREAD

**Issue by Kzoeps** [jalan/pdftotext#60]
I've already installed poppler and pkg-config but when i run `pip install pdftotext` this error pops up. I am also using anaconda and installed poppler using conda but the same error still pops up:

> ERROR: Command errored out with exit status 1:

     command: /Users/zoepa/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sk/yr8zpzq149b2nph5x2r8gn480000gn/T/pip-install-duf1kchr/pdftotext/setup.py'"'"'; __file__='"'"'/private/var/folders/sk/yr8zpzq149b2nph5x2r8gn480000gn/T/pip-install-duf1kchr/pdftotext/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/sk/yr8zpzq149b2nph5x2r8gn480000gn/T/pip-record-_x5g36d8/install-record.txt --single-version-externally-managed --compile --install-headers /Users/zoepa/anaconda3/include/python3.7m/pdftotext
         cwd: /private/var/folders/sk/yr8zpzq149b2nph5x2r8gn480000gn/T/pip-install-duf1kchr/pdftotext/
    Complete output (13 lines):
    running install
    running build
    running build_ext
    building 'pdftotext' extension
    creating build
    creating build/temp.macosx-10.7-x86_64-3.7
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/zoepa/anaconda3/include -arch x86_64 -I/Users/zoepa/anaconda3/include -arch x86_64 -DPOPPLER_CPP_AT_LEAST_0_30_0=1 -I/usr/local/include -I/Users/zoepa/anaconda3/include/python3.7m -c pdftotext.cpp -o build/temp.macosx-10.7-x86_64-3.7/pdftotext.o -Wall -mmacosx-version-min=10.9 -std=c++11
    creating build/lib.macosx-10.7-x86_64-3.7
    g++ -bundle -undefined dynamic_lookup -L/Users/zoepa/anaconda3/lib -arch x86_64 -L/Users/zoepa/anaconda3/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.7/pdftotext.o -L/usr/local/lib -lpoppler-cpp -o build/lib.macosx-10.7-x86_64-3.7/pdftotext.cpython-37m-darwin.so
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    ld: library not found for -lstdc++
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'g++' failed with exit status 1
-----------------------------------------------------
command: errored out with exit status 1: /Users/zoepa/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sk/yr8zpzq149b2nph5x2r8gn480000gn/T/pip-install-duf1kchr/pdftotext/setup.py'"'"'; __file__='"'"'/private/var/folders/sk/yr8zpzq149b2nph5x2r8gn480000gn/T/pip-install-duf1kchr/pdftotext/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/sk/yr8zpzq149b2nph5x2r8gn480000gn/T/pip-record-_x5g36d8/install-record.txt --single-version-externally-managed --compile --install-headers /Users/zoepa/anaconda3/include/python3.7m/pdftotext Check the logs for full command output.`

**Comment by jalan** [comment]
Hmm! Thought I already fixed this issue. Can you try again like this and let me know if it changes anything?

```
export MACOSX_DEPLOYMENT_TARGET=10.9
pip install pdftotext
```

**Comment by Kzoeps** [comment]
Thank you seems to work now

**Comment by jalan** [comment]
Great, thanks! I thought I had fixed this by passing `-mmacosx-version-min=10.9` to the compile stage, but maybe I have to pass it to the link stage as well.

**Comment by melaniewalsh** [comment]
I had the same issue and
`export MACOSX_DEPLOYMENT_TARGET=10.9
pip install pdftotext`
solved it

**Comment by jalan** [comment]
Thanks for confirming! Unfortunately I don't own any macs, and my current CI system doesn't have macOS Catalina. I'm going to look at setting up CI in Azure, which does have Catalina. Then I should be able to put in a fix.

**Comment by jalan** [comment]
Please don't close issues that I clearly stated I plan to work on.

**Comment by Kzoeps** [comment]
Oh so sorry my bad

**Comment by jalan** [comment]
Just pushed a release, version 2.1.5, with this fixed, as far as I can tell. Works in every combination of macOS / python / conda that I could set up in CI: https://dev.azure.com/jalanpalmer/jalanpalmer/_build/results?buildId=29
