### ISSUE TITLE
Infinite loop for extracting some PDF files

### ISSUE THREAD

**Issue by nelson-chow** [jalan/pdftotext#65]
When the program extracts some PDF files, it will loop forever to read the content of the file event it few hundred kilobytes file until exhausted the PHP max memory or reach the max execution time.

**Comment by nelson-chow** [comment]
I found out the reason, if the PDF file end with:
endstream endobj startxref 216 %%EOF 
It will loop forever. Please help to fix

**Comment by jalan** [comment]
See #46. A max execution time is the way to go.

I'm not sure what this has to do with PHP. This is a python library.
