### ISSUE TITLE
Using BytesIO with pdftotext

### ISSUE THREAD

**Issue by maclover7** [jalan/pdftotext#67]
Hi,

Thank you for working on this excellent library!

I'm trying to adapt `pdftotext` to work with pulling down PDFs from the web. I've tried to use a `BytesIO` instance to create a `File`-like interface for `pdftotext`, but I'm running into an error. Here's some sample code:

```
r = requests.get('MYPDFWEBSITE.pdf')
bytes = BytesIO(r.content)
pdf = pdftotext.PDF(bytes)
```

But I'm running into this error: `pdftotext.Error: poppler error creating document`. When I download the PDF onto my computer, and load it in via `with open()`, everything seems to work. Would appreciate any guidance/help on this

cc @jalan

**Comment by jalan** [comment]
You have the right idea, and it works, for example:

```python3
import io

import pdftotext
import requests


r = requests.get("http://www.africau.edu/images/default/sample.pdf")
b = io.BytesIO(r.content)
p = pdftotext.PDF(b)

print(len(p))
print(p[0])
```

Most likely your `requests.get` call did not fetch a PDF. It might be a 404, and it might have fetched something other than a PDF. You should check the status of your `requests.get` call before continuing, like this:

```python3
r = requests.get("http://www.africau.edu/images/default/sample.pdf.typo")
r.raise_for_status()
```

Even then, it's possible the server gives you something other than a PDF, never know. You could check if `r.headers.get("Content-Type") == "application/pdf"`, but many servers will get this wrong, so it's safer to just try to create the `pdftotext.PDF` and check for exceptions.

**Comment by maclover7** [comment]
Can confirm it was an issue with the website I was pulling the PDF down from. Thank you for your assistance!
