### ISSUE TITLE
pdftotext.Error: poppler error creating document

### ISSUE THREAD

**Issue by zhangrui-sibs** [jalan/pdftotext#68]
import pdftotext
f = open("s12859-019.pdf",'rb')
pdf = pdftotext.PDF(f)

>pdftotext.Error: poppler error creating document

pdf_doi_url: https://doi.org/10.1186/s12859-019-3104-y

**Comment by jalan** [comment]
Works fine here, using poppler 0.88 from 2020-04-27. Try again with an updated poppler.
