### ISSUE TITLE
How do I run it (pdftotext)

### ISSUE THREAD

**Issue by ripspin5** [jalan/pdftotext#69]
I don't want to make an issue for this but I am unable to see anywhere else I may get some help.

I used "pip3.7 install pdftotext" see log below, and it created: pdftotext.cpython-37m-x86_64-linux-gnu.so
So how do I run it? I believe it is a shared library

LOG:
/GS/FLP/pool/common-apps/pdftotext/pdftotext-2.1.5/
pip3.7 install  pdftotext
Processing /initrd/mnt/dev_save/pool/xenial-4.9.58/root/.cache/pip/wheels/58/79/fb/5dd8c8c5da103c697d2e79a0ef2ae89a47df9ec7d06bef8c16/pdftotext-2.1.5-cp37-cp37m-linux_x86_64.whl
Installing collected packages: pdftotext
Successfully installed pdftotext-2.1.5
/GS/FLP/pool/common-apps/pdftotext/pdftotext-2.1.5/
pip3.7 install  pdftotext
Requirement already satisfied: pdftotext in /usr/local/lib/python3.7/site-packages (2.1.5)
/GS/FLP/pool/common-apps/pdftotext/pdftotext-2.1.5/

**Comment by jalan** [comment]
It's a python library. [The README](https://github.com/jalan/pdftotext#pdftotext) has a commented example of how you might use it.

**Comment by ripspin5** [comment]
Thanks Jason, I got it going.
     On Tuesday, 18 August 2020, 12:44:01 pm AEST, Jason Alan Palmer <notifications@github.com> wrote:  
 
 


It's a python library. The README has a commented example of how you might use it.
