### ISSUE TITLE
pdftotext has unusual failures

### ISSUE THREAD

**Issue by cordeliac** [jalan/pdftotext#74]
I actually thought that pdftotext was using "measurements" and "font information"  too extract text.  More or less reading something like at 2.5" from the top, and 1.74" from the left boarder print the letters "OTH" in Times roman 14 pt italic .  Of course it's not quite so strait forward...but I didn't think pdftotext was using any sort of OCR such that is was looking at a small oval and trying to decide if that's the letter "O" or the Number "0".    But I have two successive lines in a PDF "report". Using a monospaced font like Courier.  The result varies and sometime I get extra spaces in between each character and really odd alignment issues (using -layout).  Obviously when I open up the document in Acrobat I don't see anything that leads to what causes these errors.  I've attached some TEXT (black background) and PDF (white  background) representative areas where the output seems like it "should" be better.  I occasionally have negative signs replaced by a tilde ~     I mean...they can look somewhat alike -- but I wasn't expecting an OCR type result.   Can anyone offer up an explanation?   

<img width="911" alt="Screen Shot 2020-09-17 at 1 01 25 AM" src="https://user-images.githubusercontent.com/71423515/93422434-c8b50e80-f881-11ea-8dd0-9c913119ec43.png">
<img width="904" alt="Screen Shot 2020-09-17 at 12 59 13 AM" src="https://user-images.githubusercontent.com/71423515/93422442-cc489580-f881-11ea-8225-2daf9b16dbe1.png">
<img width="904" alt="Screen Shot 2020-09-17 at 12 57 59 AM" src="https://user-images.githubusercontent.com/71423515/93422447-cc489580-f881-11ea-83dd-9972c1fffdc0.png">
<img width="704" alt="Screen Shot 2020-09-17 at 12 57 31 AM" src="https://user-images.githubusercontent.com/71423515/93422449-ce125900-f881-11ea-903c-6c4b05cdb5a5.png">

**Comment by jalan** [comment]
If you want help with a PDF, please attach it here or provide a link to it.

**Comment by jalan** [comment]
My request for a PDF demonstrating the issue has been ignored for two months. Closing

**Comment by cordeliac** [comment]
I appologize jalan, -- you may be able to tell from the samples I displayed that the PDF in question is hundreds of pages long and contains sensitive information about wages and salary information where I cannot provide the document or even an entire page from a document.  Your answer though that states there is no OCR provided most of what I needed to know.  Some scanning document archiving services run their own OCR on the document and they store this information within the PDF file somehow.  I noticed in Acrobat if I "select" the text and use copy and paste I am getting the same result.  So although it renders "correctly" the text selected doesn't match the render.  The fault must lie with the process that turned the "report" into a PDF as the invalid characters are indeed within the document.
