### ISSUE TITLE
Left margin is cut off

### ISSUE THREAD

**Issue by paulserafini** [jalan/pdftotext#76]
In the attached PDF the text is cut off on the left margin. I've reproduced this in Python 3.7.3 on Debian and Python 3.7.4 on Windows. This doesn't happen when I use the command line version of pdftotext for Linux.
[dinesh2020.pdf](https://github.com/jalan/pdftotext/files/5349533/dinesh2020.pdf)

**Comment by jalan** [comment]
Interesting! Can you tell me what the version of poppler was for each of those three cases, so I can reproduce?
 - Python 3.7.3 on Debian
 - Python 3.7.4 on Windows
 - command line version of pdftotext for Linux

**Comment by paulserafini** [comment]
Hey! Thank you for the quick response. On Windows it was version 20.10.0. On Debian it was 0.71.0-5, and I think that should apply to both the Python package and the command-line.

**Comment by jalan** [comment]
Fixed in version 2.1.6, except on very old poppler versions. Both of the versions you mentioned there should work fine. Thank you for the report, @paulserafini.
