### ISSUE TITLE
cannot run in Apple M1 architecture

### ISSUE THREAD

**Issue by LittleJymn** [jalan/pdftotext#82]
Error like this:

import pdftotext
ImportError: dlopen(/Users/huya/Library/Python/2.7/lib/python/site-packages/pdftotext.so, 2): no suitable image found.  Did find:
        /Users/huya/Library/Python/2.7/lib/python/site-packages/pdftotext.so: mach-o, but wrong architecture
        /Users/huya/Library/Python/2.7/lib/python/site-packages/pdftotext.so: mach-o, but wrong architecture

**Comment by LittleJymn** [comment]
➜  site-packages file ~/Library/Python/2.7/lib/python/site-packages/pdftotext.so
~/Library/Python/2.7/lib/python/site-packages/pdftotext.so: Mach-O 64-bit bundle x86_64

I have try "arch -x86_64 python main.py" to run, but it still not works...

**Comment by jalan** [comment]
Can you list the steps you took to get here? For example, how did you install
 - python
 - the poppler libs
 - this module

**Comment by jalan** [comment]
If you aren't willing to follow up, please do not open issues.
