### ISSUE TITLE
Documentation and Header Text

### ISSUE THREAD

**Issue by Manish07yadav** [jalan/pdftotext#85]
The documentation about this is not as great as other libraries. The best i have seen till now is documentation of "pypdf2" library (https://pythonhosted.org/PyPDF2/). I am asking for proper documentation because i want to delete all Headers and footers  text along with Page no. text from my Pdf file, so i can have a nice text file from my pdf.

**Comment by jalan** [comment]
The entirety of the documentation is available like this:

```
>>> import pdftotext
>>> help(pdftotext)
```

And just about everything you can do is shown in the example in the README.
