### ISSUE TITLE
Fails to install on Windows with Python 3.9

### ISSUE THREAD

**Issue by TheQuinbox** [jalan/pdftotext#92]
When running
```shell
pip install pdftotext
```
When on Windows, with Python 3.9, I get.
Collecting pdftotext                                                                                                    
  Using cached pdftotext-2.2.1.tar.gz (113 kB)                                                                          
Building wheels for collected packages: pdftotext                                                                       
Building wheel for pdftotext (setup.py) ... -
'<unnamed-tag>::suppress_context
pyerror
49
<unnamed-tag>
7
'<unnamed-tag>::suppress_context
pyerror
54
<unnamed-tag>
7
'<unnamed-tag>::suppress_context' 
  C:\Python39\include\cpython/pyerrors.h(66): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member 
'<unnamed-tag>::suppress_context'
ython39\include\modsupport.h(100): warning C4820: '_PyArg_Parser': '4' bytes padding added after data member '_PyA
rg_Parser::max'                                                                                                         
  C:\Python39\include\cpython/import.h(41): warning C4820: '_frozen': '4' bytes padding added after data member '_frozen
::size'                                                                                                                 
  C:\Python39\include\cpython/abstract.h(62): warning C4365: 'return': conversion from 'size_t' to 'Py_ssize_t', signed/
unsigned mismatch                                                    
C:\Python39\include\cpython/fileutils.h(54): warning C4820: '_Py_stat_struct': '4' bytes padding added after data memb
er '_Py_stat_struct::st_dev'                                                                                            
  C:\Python39\include\cpython/fileutils.h(56): warning C4820: '_Py_stat_struct': '2' bytes padding added after data memb
er '_Py_stat_struct::st_mode'                                                                                           
  C:\Python39\include\cpython/fileutils.h(60): warning C4820: '_Py_stat_struct': '4' bytes padding added after data memb
er '_Py_stat_struct::st_rdev'
C:\Python39\include\cpython/fileutils.h(63): warning C4820: '_Py_stat_struct': '4' bytes padding added after data memb
er '_Py_stat_struct::st_atime_nsec'
C:\Python39\include\cpython/fileutils.h(65): warning C4820: '_Py_stat_struct': '4' bytes padding added after data memb
er '_Py_stat_struct::st_mtime_nsec'                                                                                     
  C:\Python39\include\cpython/fileutils.h(69): warning C4820: '_Py_stat_struct': '4' bytes padding added after data memb
er '_Py_stat_struct::st_reparse_tag'                                                                                    
  pdftotext.cpp(3): fatal error C1083: Cannot open include file: 'poppler/cpp/poppler-document.h': No such file or direc
tory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\
HostX86\\x64\\cl.exe' failed with 
i
code 2     
----------------------------------------     
  ERROR: Failed building wheel for pdftotext                                                                            
  Running setup.py clean for pdftotext                                                                                  
Failed to build pdftotext                                                                                               
Installing collected packages: pdftotext                                                                                
Running setup.py install for pdftotext ... -
r '<unnamed-tag>::suppress_context'                                                                                     
    C:\Python39\include\cpython/pyerrors.h(49): warning C4820: '<unnamed-tag>': '7' bytes padding added after data membe
r '<unnamed-tag>::suppress_context'                                                                                     
    C:\Python39\include\cpython/pyerrors.h(54): warning C4820: '<unnamed-tag>': '7' bytes padding added after data membe
r '<unnamed-tag>::suppress_context'                                                                                     
ERROR: Command errored out with exit status 1: 'C:\Python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize;
 sys.argv[0] = '"'"'C:\\Users\\quinm\\AppData\\Local\\Temp\\pip-install-e0oi3j3j\\pdftotext_01489c42f66a4f68bfe46bc9cc64
e3f0\\setup.py'"'"'; __file__='"'"'C:\\Users\\quinm\\AppData\\Local\\Temp\\pip-install-e0oi3j3j\\pdftotext_01489c42f66a4
f68bfe46bc9cc64e3f0\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) els
e io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.c
lose();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\quinm\AppData\Local\Temp\pip-record-_7e
f1xp_\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Python39\Include\pdftotext
' Check the logs for full command output.                                                                               

Any ideas?

**Comment by jalan** [comment]
Please see #16.

**Comment by MunavvarNazarov** [comment]
conda install -c conda-forge poppler
