### ISSUE TITLE
Extract text from scanned pdfs

### ISSUE THREAD

**Issue by mapto** [jalan/pdftotext#93]
PDF is a diverse format and users often do not appreciate the complexity behind what they see. This is why often they wonder why tools like pdftotext are unable to extract the text from their document. One very common use case is PDFs generated e.g. by scanners where each page is actually an image of a scanned page. Thanks to OCR tools like tesseract extracting such texts is actually quite easy. Of course the caveat of text ordering would still remain, but this is also a problem of other texts extracted from PDFs, so I wouldn't consider it as unexpected by the user. I'm about to implement such routine. This issue is rather meant as a question whether you'd be interested to do it as a pull request for your library? Otherwise I will do it as a separate project?

**Comment by stefan6419846** [comment]
I do not think that it makes sense to pull this into this project, as this mostly are the Python bindings for the *pdftotext* library (from Poppler). There already are Python bindings for Tesseract itself, so using these appears to make more sense for your use case.

**Comment by jalan** [comment]
> I do not think that it makes sense to pull this into this project, as this mostly are the Python bindings for the _pdftotext_ library (from Poppler). There already are Python bindings for Tesseract itself, so using these appears to make more sense for your use case.

I agree
